---
- name: Pull docker image of Calculator
  hosts: all
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull docker685/spe_mini_proj_scientific_calc

    - name: running container
      shell: docker run -it -d docker685/spe_mini_proj_scientific_calc